# Generated by Django 5.2.8 on 2025-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marca_produto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, default='')),
                ('cor_principal', models.CharField(default='#111111', max_length=7)),
                ('modo_escuro', models.BooleanField(default=False)),
                ('telefone_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('endereco', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
