# Generated by Django 5.2.8 on 2025-12-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaoloja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos',
            field=models.ManyToManyField(blank=True, to='core.tamanho'),
        ),
    ]
