# Generated by Django 5.2.8 on 2025-12-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tamanho_produto_tamanhos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='configuracaoloja',
            options={'ordering': ['id'], 'verbose_name_plural': 'Configurações da Loja'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Produtos'},
        ),
    ]
